services:
  db:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: my_spring_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pgdata:
